# Smoke test: build, generate both ASCII + Chinese, print both
param(
    [string]$PrinterName = "Xprinter XP-360B #2"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Smoke Test: 020 barcode" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

# 1. Build
Write-Host "`n[1/4] Building..." -ForegroundColor Yellow
& "C:\Program Files\Microsoft Visual Studio\18\Community\Common7\Tools\Launch-VsDevShell.ps1" -SkipAutomaticLocation
cmake --build "$root\out\build\x64-Debug" 2>&1
if ($LASTEXITCODE -ne 0) { throw "Build failed" }

# 2. Generate labels (both ASCII + Chinese in one run)
Write-Host "`n[2/4] Generating labels..." -ForegroundColor Yellow
Push-Location $root
$output = & "$root\out\build\x64-Debug\labelprint_demo.exe" 2>&1
Pop-Location
if ($LASTEXITCODE -ne 0) { throw "Generator failed" }
Write-Host "       OK"

# 3. Print ASCII label
Write-Host "`n[3/4] Printing ASCII label..." -ForegroundColor Yellow
& "$root\RawTSPL.ps1" -PrinterName $PrinterName -TsplFile "label_medical.tspl"
Write-Host "       OK"

# 4. Print Chinese label (generated by TsplBitmapBackend in step 2)
Write-Host "`n[4/4] Printing Chinese label..." -ForegroundColor Yellow
& "$root\RawTSPL.ps1" -PrinterName $PrinterName -TsplFile "label_medical_cn_new.prn"
Write-Host "       OK"

Write-Host "`n========================================" -ForegroundColor Green
Write-Host "  Smoke test passed" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
